### ISSUE TITLE
[iOS] Crash on com.apple.coreaudio.avfaudio: required condition is false: IsFormatSampleRateAndChannelCountValid(format)

### ISSUE THREAD

**Issue by jamsch** [wenkesj/react-native-voice#50] opened 2017-11-22 22:14 UTC
Hi, I'm getting an error while starting up speech recognition on an iPad Air 2. Not sure what is causing the issue. 

### Environment
```json
"device": {
    "family": "iOS",
    "arch": "arm64",
    "storage_size": 63989493760,
    "free_memory": 51675136,
    "memory_size": 2084569088,
    "boot_time": "2017-11-13T07:29:50Z",
    "model": "iPad5,4",
    "usable_memory": 1687126016,
    "type": "device"
},

"os": {
    "rooted": false,
    "kernel_version": "Darwin Kernel Version 17.2.0: Fri Sep 29 18:14:52 PDT 2017; root:xnu-4570.20.62~4/RELEASE_ARM64_T7001",
    "version": "11.1.1",
    "build": "15B150",
    "type": "os",
    "name": "iOS"
}
```

### Exception

```
Application threw exception com.apple.coreaudio.avfaudio: required condition is false: IsFormatSampleRateAndChannelCountValid(format)

Originated at or in a subcall of folly::Expected<long long, folly::ConversionCode> folly::detail::str_to_integral<long long>(folly::Range<char const*>*)
```

**Comment by jamsch** [comment] 2017-11-23 00:18
Narrowed it down to the following:

```objectivec
 [inputNode installTapOnBus:0 bufferSize:1024 format:recordingFormat block:^(AVAudioPCMBuffer * _Nonnull buffer, AVAudioTime * _Nonnull when) {
    if (self.recognitionRequest != nil) {
        [self.recognitionRequest appendAudioPCMBuffer:buffer];
    }
}];
```

**Comment by jamsch** [comment] 2017-11-24 00:22
Just got my hands on an iPad (2017) model and the same issue occurs on it as well.

```javascript
contexts": {
"device": {
"family": "iOS",
"arch": "arm64",
"storage_size": 31999954944,
"free_memory": 41123840,
"memory_size": 2075656192,
"boot_time": "2017-11-24T00:07:53Z",
"model": "iPad6,11",
"usable_memory": 1944502272,
"type": "device"
},
"os": {
"rooted": false,
"kernel_version": "Darwin Kernel Version 17.2.0: Fri Sep 29 18:14:51 PDT 2017; root:xnu-4570.20.62~4/RELEASE_ARM64_S8000",
"version": "11.1.2",
"build": "15B202",
"type": "os",
"name": "iOS"
}
},
```

**Comment by mrwordev** [comment] 2017-11-24 02:49
I have the same issue here, It only happen on real device only. This include iPhone5, iPhone6s, iPhone7. No luck on fixing this so far.

**Comment by Damnum** [comment] 2017-11-24 02:57
Same issue here, this is really holding us back from going into production

**Comment by mrwordev** [comment] 2017-11-24 04:23
@jamsch I have manage to make it work by adding category and a few function call there.
In `Voice.m` starting from line 38
```objectivec
    NSError* audioSessionError = nil;
    self.audioSession = [AVAudioSession sharedInstance];
    [self.audioSession setCategory:AVAudioSessionCategoryRecord error:&audioSessionError];
    
    if (audioSessionError != nil) {
        [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
        return;
    }
    [self.audioSession setMode:AVAudioSessionModeMeasurement error:&audioSessionError];
    if (audioSessionError != nil) {
        [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
        return;
    }
    [self.audioSession setActive:YES withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:&audioSessionError];
    if (audioSessionError != nil) {
        [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
        return;
    }

```

**Comment by jamsch** [comment] 2017-11-24 06:48
@mrwordev 
Haven't had the chance to test thoroughly but it did seem to work fine although using the speech recognition while any audio is currently playing (e.g. using react-native-sound) seems to break. I'll be out for the weekend but I'll test it further on Monday.

**Comment by jamsch** [comment] 2017-11-27 02:58
I don't know much about the internals of iOS but it looks like changing the category of a shared audio session will likely interrupt any audio. So this means that using `setCategory:AVAudioSessionCategoryRecord` will interrupt any currently playing audio in the app. `react-native-sound` has an option to set the category. We should probably do the same for this package. `PlayAndRecord` in particular allows both playing/recording at the same time.

I'm still having problems getting the speech recognition to actually fire/stop. One issue I noticed is that if the `startSpeech` function were called when speech recognition already started there's no callback.

**Comment by ohtangza** [comment] 2017-11-27 09:27
@ghsdh3409 Please keep track of this issue.

**Comment by zxcal** [comment] 2017-11-28 09:04
In my case, the error occurs when I start recognizing immediately after the destroy function. The time destroy function return the promise is not after it truly destroy the recognition. I use setTimeout to delay the restart to about 500 ms to make sure that the recognition is destroyed completely. This solve my problem.

**Comment by dmwallace** [comment] 2018-02-06 02:52
Also getting this issue when including react-native-sound in my project

**Comment by ainulya16** [comment] 2018-03-19 10:27
Sound not playing after modify line 38 on Voice.m

Any solution?

**Comment by rajkissu** [comment] 2018-04-07 08:28
I'm facing this issue of no sound as well. After adding code on line 38 as per @mrwordev's suggestion, `react-native-voice` works on iOS - but it kills sound on other modules like `react-native-tts`

Anyone managed to find a solution?

**Comment by jamsch** [comment] 2018-04-07 09:24
I'll be using react-native-voice on a semi large production app on iOS quite soon with a fork of this with a few slight fixes. https://github.com/jamsch/react-native-voice/

The main differences are:
* The audio category is reverted back to the original category set prior to using speech recognition
* During speech recognition it sets the audio category to either PlayAndRecord or Record depending on whether the user is playing audio.
* Should take bluetooth/wireless sound output devices in to account
* A method for checking whether speech recognition is ready on iOS. 
* try/catch blocks around code prone to crashing the app, which instead throws an error on the JavaScript side, which allows the user to rather be notified if speech recognition failed.
* Copied setAudioCategory API from react-native-sound in case the user wants to control the audio category.

**Comment by ohtangza** [comment] 2018-04-08 06:00
@jamsch Sounds very interesting! I would love to review your PR. :)

**Comment by weihuali0509** [comment] 2018-04-10 20:02
This is not working. Any ETA for the PR @jamsch ? Thanks!

**Comment by abhishekbhardwaj** [comment] 2018-04-10 23:03
@jamsch Great work man! Would it be possible for you to PR the changes?

**Comment by jamsch** [comment] 2018-04-13 00:14
The changes up till https://github.com/jamsch/react-native-voice/commit/ca0485de2d467a3339269e2e2039cc91b4438dd8  have been live in a production app the past few days. There's been some significant changes since then, mostly around handling errors.

According to my error tracker, one user has experienced the issue:
`NSInternalInconsistencyException: SFSpeechAudioBufferRecognitionRequest cannot be re-used`

**Comment by abhishekbhardwaj** [comment] 2018-04-14 11:35
@jamsch Have you tried your changes on `Android` too or just iOS? Cuz it kept giving me 'speech unavailable' on Android.

**Comment by jamsch** [comment] 2018-04-14 11:44
@abhishekbhardwaj On and off but it hasn't been tested the past few changes. The "not_available" is unusual though because the functionality behind that API shouldn't have changed besides changing from a callback to a promise. It does now check whether speech recognition is available when starting speech recognition which it didn't do previously. You may want to try commenting out lines 119-121 -- https://github.com/jamsch/react-native-voice/blob/master/index.js#L119

**Comment by abhishekbhardwaj** [comment] 2018-04-16 10:05
@jamsch perfect. Thank you man!

**Comment by anaerobic** [comment] 2018-04-20 03:02
@jamsch I am also seeing an error in an Android API 24 simulator using the `VoiceTest` example and the following in my package.json:
```
"react-native": "0.54.1",
...
"react-native-voice": "git+https://github.com/jamsch/react-native-voice.git",
```

and the error in logcat is:
```
[Info] 04-19 22:38:54.094  3847  3878 E ReactNativeJS: { code: 'not_available',
04-19 22:38:54.094  3847  3878 E ReactNativeJS:   line: 143090,
04-19 22:38:54.094  3847  3878 E ReactNativeJS:   column: 18,
04-19 22:38:54.094  3847  3878 E ReactNativeJS:   sourceURL: 'http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false' }
```

i'll be happy to assist further if needed, thanks much!

**Comment by anaerobic** [comment] 2018-04-20 03:16
actually i see now this is thrown when speech recognition is considered to be not available on the device:
https://github.com/wenkesj/react-native-voice/compare/master...jamsch:master#diff-168726dbe96b3ce427e7fedce31bb0bcR117

**Comment by anaerobic** [comment] 2018-04-20 05:28
okay, I found that @jamsch/master works on a connected android device after deleting the android/build/generated+intermediate+tmp directories and rebuilding all of that, so the "not_available" problem might be specific to virtual android devices.

**Comment by alvaro1728** [comment] 2018-05-10 18:12
@jamsch Thanks for all the fixes. I'd like to use your fork in my project. How do I npm install it?

**Comment by folofse** [comment] 2018-06-07 07:56
@jamsch I found that the "NSInternalInconsistencyException: SFSpeechAudioBufferRecognitionRequest cannot be re-used" -problem might be caused by a bug in react-navigator which seams to mount the views twice. It works fine when all is setup and initialized, but if the function runs for the first time and the gets the "Allow microphone" - alert, directly when they click Allow the app crashes due to this problem. The error occurs when Voice.start() on this line in  Voice.m `self.recognitionTask = [self.speechRecognizer recognitionTaskWithRequest:self.recognitionRequest resultHandler:^(SFSpeechRecognitionResult * _Nullable result, NSError * _Nullable error) {`. I tried to fix the problem by throttle the Voice.start() calls in the view, but the views seams to get mounted from different instances and they calls componentDidMount at the same time so its a bit tricky to get it to work.

**Comment by ManhVuTien** [comment] 2018-07-27 03:53
@folofse 
- (void) setupAndStartRecognizing:(NSString*)localeStr {
    if(self.sessionId){
        return;
    }

error when I add this code

**Comment by sibelius** [comment] 2018-11-04 09:57
@jamsch in your fork have you solved your problem ? https://github.com/jamsch/react-native-voice

are you willing to send a PR to fix this?

**Comment by sibelius** [comment] 2018-11-04 20:04
this is probably fixed on master, based on this https://github.com/wenkesj/react-native-voice/commit/fade2bddbec6be35165e8feee7cfa6967b93c669

can anybody confirm this?

**Comment by sibelius** [comment] 2018-11-05 11:40
fixed on master

**Closed by sibelius** 2018-11-05 11:40 UTC

**Comment by zainmusani** [comment] 2018-11-12 15:16
Working on iOS device and Crashing on iOS Simulator

**Comment by kingarawana** [comment] 2018-12-07 21:05
On iOS 12 it crashes on device but works on simulator. Tried on iPad Pro 3 and iPhone 6 device.

**Comment by tronin** [comment] 2019-01-02 16:00
The same problem with react-native-tts.

**Comment by ddgromit** [comment] 2019-05-02 20:40
If anyone is still having this problem, first make sure you're using the `master` version of this package.  Version 0.2.6 that is published on NPM is a year old and doesn't contain the fix.

Link directly to the github in your dependencies:
```
    "react-native-voice": "wenkesj/react-native-voice",
```

**Comment by monggos** [comment] 2019-05-03 07:46
@ddgromit  still having the issue of..

on first init, all just fine until you need to start again to capture the voice for the second time.

is there any solution yet? btw, i am using the master version 0.2.6

thanks!

**Comment by rajeevAgilehub** [comment] 2019-05-21 06:07
> fixed on master

I copied Voice.m from master and replace the existing code (node_modules/react-native-voice/ios/Voice/Voice.m), it fixed the conflict problem between react-native-voice and react-native-tts 👍🕺🏿

**Comment by monggos** [comment] 2019-05-21 06:15
@rajeevAgilehub  i did fixed my issue by using this package instead. https://github.com/Evgen74/react-native-voice

i think he fixed it same way as yours?

**Comment by lukemcgregor** [comment] 2019-08-14 02:29
Im getting this issue in 0.3.0, is it still not fixed in that version? or is this a regression of something?

**Comment by teslavitas** [comment] 2019-09-30 09:39
I am getting this event with the version from wenkesj/react-native-voice . Sometimes after 20-30 cycles of stop/start, sometimes faster.

**Comment by dilipsuthar97** [comment] 2022-06-29 09:21
@jamsch 
> @jamsch I have manage to make it work by adding category and a few function call there. In `Voice.m` starting from line 38
> 
> ```objc
>     NSError* audioSessionError = nil;
>     self.audioSession = [AVAudioSession sharedInstance];
>     [self.audioSession setCategory:AVAudioSessionCategoryRecord error:&audioSessionError];
>     
>     if (audioSessionError != nil) {
>         [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
>         return;
>     }
>     [self.audioSession setMode:AVAudioSessionModeMeasurement error:&audioSessionError];
>     if (audioSessionError != nil) {
>         [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
>         return;
>     }
>     [self.audioSession setActive:YES withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:&audioSessionError];
>     if (audioSessionError != nil) {
>         [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
>         return;
>     }
> ```

Can you please share that Voice.m entire file?
because it seems different at my side.

**Comment by mschouhan123** [comment] 2022-10-12 06:24
> @jamsch
> 
> > @jamsch I have manage to make it work by adding category and a few function call there. In `Voice.m` starting from line 38
> > ```objc
> >     NSError* audioSessionError = nil;
> >     self.audioSession = [AVAudioSession sharedInstance];
> >     [self.audioSession setCategory:AVAudioSessionCategoryRecord error:&audioSessionError];
> >     
> >     if (audioSessionError != nil) {
> >         [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
> >         return;
> >     }
> >     [self.audioSession setMode:AVAudioSessionModeMeasurement error:&audioSessionError];
> >     if (audioSessionError != nil) {
> >         [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
> >         return;
> >     }
> >     [self.audioSession setActive:YES withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:&audioSessionError];
> >     if (audioSessionError != nil) {
> >         [self sendResult:RCTMakeError([audioSessionError localizedDescription], nil, nil) :nil :nil :nil];
> >         return;
> >     }
> > ```
> 
> Can you please share that Voice.m entire file? because it seems different at my side.

Yes I am also facing the same Problem. Please share full file.

**Comment by jamsch** [comment] 2025-07-11 09:46
@YashYash as I mentioned earlier in this thread some years ago, you'll likely have to manage the iOS audio category since you're working with video playback as well. This library does not provide those helpers but fwiw I have implemented them in my alternative library.

Getting the category
https://github.com/jamsch/expo-speech-recognition?tab=readme-ov-file#getaudiosessioncategoryandoptionsios-ios-only

Setting the category 
https://github.com/jamsch/expo-speech-recognition?tab=readme-ov-file#setaudiosessionactiveiosvalue-boolean-options--notifyothersondeactivation-boolean--void

And there's also an `iosCategory` option to allow you to configure the category when speech recognition starts.


It's a pretty simple implementation that you could even implement yourself with a local Expo module: https://docs.expo.dev/modules/get-started/#adding-a-new-module-to-an-existing-application

**Comment by YashYash** [comment] 2025-07-11 12:10
Oh nice! Thanks @jamsch really appreciate the help. I will give this a try tomorrow. I just got my current work around working in a really hacky way using `react-native-webview` to render videos instead of using `react-native-video` since I don't need the video I am playing to play any audio. Just had a quick look at the docs you shared. This is exactly what I am looking for. Thanks again.
